from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
import shutil
import os
#from main import Ui_MainWindow


class Ui_CMDS(object):




    def push_Name(self, path):
        global NAME
        NAME = path




    def check(self, test, command):
        if test.isChecked() == True:
            shutil.copy("ressources/commands/{}.js".format(command), NAME + "/commands/")

        else:

            os.remove("{}/commands/".format(NAME) + command + ".js")


    def setupUi(self, MainWindow):


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 720)
        MainWindow.setMinimumSize(QtCore.QSize(720, 720))
        MainWindow.setMaximumSize(QtCore.QSize(720, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 47, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 47, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(15)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.cinfi_lb = QtWidgets.QLabel(self.centralwidget)
        self.cinfi_lb.setEnabled(True)
        self.cinfi_lb.setGeometry(QtCore.QRect(26, 0, 651, 52))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.cinfi_lb.setFont(font)
        self.cinfi_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cinfi_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.cinfi_lb.setObjectName("cinfi_lb")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(26, 52, 677, 625))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(26, 26, 261, 313))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(3, 27, 235, 287))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.uich = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.uich.setObjectName("uich")
        self.gridLayout.addWidget(self.uich, 4, 0, 1, 1)
        self.kickch = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.kickch.setObjectName("kickch")
        self.gridLayout.addWidget(self.kickch, 1, 0, 1, 1)
        self.unmutech = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.unmutech.setObjectName("unmutech")
        self.gridLayout.addWidget(self.unmutech, 3, 0, 1, 1)
        self.mutech = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.mutech.setObjectName("mutech")
        self.gridLayout.addWidget(self.mutech, 2, 0, 1, 1)
        self.banch = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.banch.setObjectName("banch")
        self.gridLayout.addWidget(self.banch, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(364, 26, 287, 313))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(3, 27, 261, 287))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ballch = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.ballch.setObjectName("ballch")
        self.gridLayout_2.addWidget(self.ballch, 4, 0, 1, 1)
        self.avatarch = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.avatarch.setObjectName("avatarch")
        self.gridLayout_2.addWidget(self.avatarch, 5, 0, 1, 1)
        self.asciich = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.asciich.setObjectName("asciich")
        self.gridLayout_2.addWidget(self.asciich, 1, 0, 1, 1)
        self.cardch = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.cardch.setObjectName("cardch")
        self.gridLayout_2.addWidget(self.cardch, 6, 0, 1, 1)
        self.memech = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.memech.setObjectName("memech")
        self.gridLayout_2.addWidget(self.memech, 7, 0, 1, 1)
        self.acch = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.acch.setObjectName("acch")
        self.gridLayout_2.addWidget(self.acch, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(26, 365, 625, 287))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(338, 26, 287, 209))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.saych = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.saych.setObjectName("saych")
        self.gridLayout_2.addWidget(self.saych, 3, 0, 1, 1)
        self.restartch = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.restartch.setObjectName("restartch")
        self.gridLayout_4.addWidget(self.restartch, 2, 0, 1, 1)
        self.Sich = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.Sich.setObjectName("Sich")
        self.gridLayout_4.addWidget(self.Sich, 4, 0, 1, 1)
        self.Pingch = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.Pingch.setObjectName("Pingch")
        self.gridLayout_4.addWidget(self.Pingch, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 26, 313, 209))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Welch = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.Welch.setObjectName("Welch")
        self.gridLayout_3.addWidget(self.Welch, 2, 0, 1, 1)
        self.surveych = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.surveych.setObjectName("surveych")
        self.gridLayout_3.addWidget(self.surveych, 0, 0, 1, 1)
        self.stopch = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.stopch.setObjectName("stopch")
        self.gridLayout_3.addWidget(self.stopch, 3, 0, 1, 1)
        self.runch = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.runch.setObjectName("runch")
        self.gridLayout_3.addWidget(self.runch, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        

        self.clearch = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.clearch.setObjectName("clearch")
        self.gridLayout_4.addWidget(self.clearch, 5, 0, 1, 1)


        self.uich.stateChanged.connect(lambda:self.check(self.uich, "userinfo"))
        self.kickch.stateChanged.connect(lambda:self.check(self.kickch, "kick"))
        self.unmutech.stateChanged.connect(lambda:self.check(self.unmutech, "unmute"))
        self.mutech.stateChanged.connect(lambda:self.check(self.mutech, "mute"))
        self.banch.stateChanged.connect(lambda:self.check(self.banch, "ban"))
        self.ballch.stateChanged.connect(lambda:self.check(self.ballch, "8ball"))
        self.asciich.stateChanged.connect(lambda:self.check(self.asciich, "ascii"))
        self.acch.stateChanged.connect(lambda:self.check(self.acch, "achievement"))
        self.saych.stateChanged.connect(lambda:self.check(self.saych, "say"))
        self.Sich.stateChanged.connect(lambda:self.check(self.Sich, "serverinfo"))
        self.Pingch.stateChanged.connect(lambda:self.check(self.Pingch, "ping"))
        self.Welch.stateChanged.connect(lambda:self.check(self.Welch, "welcome"))
        self.surveych.stateChanged.connect(lambda:self.check(self.surveych, "survey"))
        self.stopch.stateChanged.connect(lambda:self.check(self.stopch, "stop"))
        self.runch.stateChanged.connect(lambda:self.check(self.runch, "run"))
        self.memech.stateChanged.connect(lambda:self.check(self.memech, "meme"))
        self.restartch.stateChanged.connect(lambda:self.check(self.restartch, "restart"))
        self.avatarch.stateChanged.connect(lambda:self.check(self.avatarch, "avatar"))
        self.cardch.stateChanged.connect(lambda:self.check(self.cardch, "card"))
        self.clearch.stateChanged.connect(lambda:self.check(self.clearch, "clear"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)






    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Discord Bot Maker script"))
        self.cinfi_lb.setText(_translate("MainWindow", "Commands"))
        self.groupBox.setTitle(_translate("MainWindow", "Moderation"))
        self.uich.setText(_translate("MainWindow", "userinfo"))
        self.kickch.setText(_translate("MainWindow", "kick"))
        self.unmutech.setText(_translate("MainWindow", "unmute"))
        self.mutech.setText(_translate("MainWindow", "mute"))
        self.banch.setText(_translate("MainWindow", "ban"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fun"))
        self.ballch.setText(_translate("MainWindow", "8ball"))
        self.clearch.setText(_translate("MainWindow", "Clear"))
        self.avatarch.setText(_translate("MainWindow", "avatar"))
        self.asciich.setText(_translate("MainWindow", "Ascii"))
        self.cardch.setText(_translate("MainWindow", "card"))
        self.memech.setText(_translate("MainWindow", "meme"))
        self.acch.setText(_translate("MainWindow", "Achievement"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Utils"))
        self.saych.setText(_translate("MainWindow", "Say"))
        self.restartch.setText(_translate("MainWindow", "Restart"))
        self.Sich.setText(_translate("MainWindow", "Serverinfo"))
        self.Pingch.setText(_translate("MainWindow", "Ping"))
        self.Welch.setText(_translate("MainWindow", "welcome"))
        self.surveych.setText(_translate("MainWindow", "Survey"))
        self.stopch.setText(_translate("MainWindow", "Stop"))
        self.runch.setText(_translate("MainWindow", "Run"))

        info = QMessageBox()
        info.setWindowTitle("Commands maker")
        info.setText("When your done you can close all windows")
        info.setIcon(QMessageBox.Information)

        x = info.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CMDS()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
