
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication

import os
import shutil
import threading
from playsound import *
from cmds import Ui_CMDS
from run import Ui_Form
import sys
from npm.bindings import npm_run
import json
from nodejs.bindings import node_run


threading.Thread(target=playsound, args=('ui/music.mp3',), daemon=True).start()
class Ui_MainWindow(object):

    scriptDir = os.path.dirname(os.path.realpath("_file_"))

    def runbotfunc(self):
        self.window2 = QtWidgets.QMainWindow()
        self.run = Ui_Form()
        self.run.setupUi(self.window2)
        self.window2.show()





    def generate(self):
          global NAME
          msgbox = QMessageBox()
          msgbox.setWindowTitle("Missing arguments")
          msgbox.setText("One or multiple arguments aren't filled")
          msgbox.setIcon(QMessageBox.Information)
          NAME = self.name_entry.text()

          if self.token_entry.text() == "" or self.name_entry.text() == "" or self.id_entry.text() == "" or self.prefix_entry.text() == "":
              x = msgbox.exec_()
          else:

              NAME = self.name_entry.text()
              ID = self.id_entry.text()
              PREFIX = self.prefix_entry.text()


              tokenreal = {
                  'TOKEN' : '{}'.format(self.token_entry.text())
              }

              prefixreal = {
                  "PREFIX" : "{}".format(PREFIX)
              }

              os.makedirs(NAME)
              os.makedirs("{}/commands".format(NAME))
              os.makedirs("{}/sources".format(NAME))
              tk = json.dumps(tokenreal)
              tokenfile = open("{}/token.json".format(NAME), 'w')
              tokenfile.write(tk)
              tokenfile.close()
              prf = json.dumps(prefixreal)
              prffile = open("{}/prefix.json".format(NAME), 'w')
              prffile.write(prf)
              prffile.close()
              shutil.copy("ressources/index.js", NAME)
              shutil.copy("ressources/Procfile", NAME)
              shutil.copy("ressources/commands/whoami.js", NAME + "/commands/")
              os.chdir(NAME)
              infobox = QMessageBox()
              infobox.setWindowTitle("Time Information")
              infobox.setText("Were installing the required librairies...")
              infobox.setIcon(QMessageBox.Information)
              infobox.setInformativeText("This will take some time, please don't kill the app! Press Ok to continue")
              x = infobox.exec_()
              npm_run('init', '-y')
              print("Installing fs")
              npm_run("install", "--save","fs")
              print("Installing djs-commands")
              npm_run("install", "--save","djs-commands")
              print("Installing discord.js")
              npm_run("install", "--save","discord.js")
              print("Installing canvas")
              npm_run("install", "--save","canvas")
              print("Installing figlet")
              npm_run("install", "--save","figlet")
              print("Installing random-puppy")
              npm_run("install", "--save","random-puppy")
              print("Installing ytdl")
              npm_run("install", "--save","ytdl-core")
              print("Installing child_process")
              npm_run("install", "--save","child_process")



              os.chdir("../")
              finishbox = QMessageBox()
              finishbox.setWindowTitle("Bot finished")
              finishbox.setText("Your bot has been saved to {}".format(NAME))
              finishbox.setIcon(QMessageBox.Information)
              finishbox.setInformativeText("Your bot invite link: {}".format("https://discord.com/api/oauth2/authorize?client_id=" + ID + "&permissions=8&scope=bot"))
              x = finishbox.exec_()

              self.window = QtWidgets.QMainWindow()
              self.ui = Ui_CMDS()
              self.ui.push_Name(NAME)
              self.ui.setupUi(self.window)
              self.window.show()





    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 480)

        MainWindow.setMinimumSize(QtCore.QSize(575, 480))
        MainWindow.setMaximumSize(QtCore.QSize(575, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 47, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 47, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 170, 181, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 39, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(15)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.name_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.name_entry.setGeometry(QtCore.QRect(312, 67, 235, 27))
        self.name_entry.setStatusTip("")
        self.name_entry.setObjectName("name_entry")
        self.cinfi_lb = QtWidgets.QLabel(self.centralwidget)
        self.cinfi_lb.setEnabled(True)
        self.cinfi_lb.setGeometry(QtCore.QRect(156, 0, 261, 49))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.cinfi_lb.setFont(font)
        self.cinfi_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cinfi_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.cinfi_lb.setObjectName("cinfi_lb")
        self.name_lb = QtWidgets.QLabel(self.centralwidget)
        self.name_lb.setGeometry(QtCore.QRect(0, 52, 261, 52))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.name_lb.setFont(font)
        self.name_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lb.setObjectName("name_lb")
        self.gen_butt = QtWidgets.QPushButton(self.centralwidget)
        self.gen_butt.setGeometry(QtCore.QRect(156, 416, 261, 27))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.gen_butt.setFont(font)
        self.gen_butt.setObjectName("gen_butt")
        self.id_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.id_entry.setGeometry(QtCore.QRect(312, 301, 235, 27))
        self.id_entry.setObjectName("id_entry")
        self.id_lb = QtWidgets.QLabel(self.centralwidget)
        self.id_lb.setGeometry(QtCore.QRect(0, 286, 261, 52))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.id_lb.setFont(font)
        self.id_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.id_lb.setObjectName("id_lb")
        self.token_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.token_entry.setGeometry(QtCore.QRect(312, 146, 235, 27))
        self.token_entry.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.token_entry.setMouseTracking(True)
        self.token_entry.setInputMask("")
        self.token_entry.setText("")
        self.token_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.token_entry.setDragEnabled(False)
        self.token_entry.setObjectName("token_entry")
        self.token_lb = QtWidgets.QLabel(self.centralwidget)
        self.token_lb.setGeometry(QtCore.QRect(0, 130, 205, 52))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.token_lb.setFont(font)
        self.token_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.token_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.token_lb.setWordWrap(True)
        self.token_lb.setObjectName("token_lb")
        self.prefix_lb = QtWidgets.QLabel(self.centralwidget)
        self.prefix_lb.setGeometry(QtCore.QRect(0, 206, 235, 52))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.prefix_lb.setFont(font)
        self.prefix_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.prefix_lb.setObjectName("prefix_lb")
        self.prefix_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.prefix_entry.setGeometry(QtCore.QRect(312, 222, 235, 27))
        self.prefix_entry.setObjectName("prefix_entry")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 32))
        self.menubar.setMouseTracking(True)
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuBot = QtWidgets.QMenu(self.menubar)
        self.menuBot.setObjectName("menuBot")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionNew.setVisible(False)
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setCheckable(False)
        self.actionRun.setObjectName("actionRun")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setVisible(True)
        self.actionQuit.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionQuit.setObjectName("actionQuit")
        self.menuBot.addAction(self.actionNew)
        self.menuBot.addAction(self.actionRun)
        self.menuBot.addSeparator()
        self.menuBot.addAction(self.actionQuit)
        self.menubar.addAction(self.menuBot.menuAction())

        self.gen_butt.clicked.connect(self.generate)
        self.actionRun.triggered.connect(self.runbotfunc)
        self.actionQuit.triggered.connect(lambda: sys.exit())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Discord Bot Maker script"))
        self.name_entry.setToolTip(_translate("MainWindow", "Your bot name here"))
        self.cinfi_lb.setText(_translate("MainWindow", "Configuration"))
        self.name_lb.setText(_translate("MainWindow", "Bot Name:"))
        self.gen_butt.setText(_translate("MainWindow", "Generate"))
        self.id_entry.setToolTip(_translate("MainWindow", "The client ID of your application"))
        self.id_lb.setText(_translate("MainWindow", "Client ID:"))
        self.token_entry.setToolTip(_translate("MainWindow", "Your bot token here"))
        self.token_lb.setText(_translate("MainWindow", "Bot Token:"))
        self.prefix_lb.setText(_translate("MainWindow", "Prefix:"))
        self.menuBot.setTitle(_translate("MainWindow", "Bot"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new bot"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setStatusTip(_translate("MainWindow", "Run a bot"))
        self.actionRun.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit the app"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))




if __name__ == "__main__":


    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
